gpuevents:
  GPUHang:
    name: "GPUHang"
    description: "GPU Hang"
    duration_threshold: 60s
    level: fatal
    query_interval_after_abnormal: 10s
    abnormal_detected_times: 5
    check_items:
      pwr:
        threshold: 100
        compare: low
      gclk:
        threshold: 1400
        compare: high
      smclk:
        threshold: 1400
        compare: high
      sm:
        threshold: 95
        compare: high
      mem:
        threshold: 5
        compare: low
      pviol:
        threshold: 5
        compare: low
      rxpci:
        threshold: 300 # MB/s
        compare: low
      txpci:
        threshold: 300 # MB/s
        compare: low
    check_items_by_model:
      - model: "0x233010de"
        override:
          pwr:
            threshold: 160
            compare: low
          gclk:
            threshold: 1900
            compare: high
          smclk:
            threshold: 1900
            compare: high
      - model: "0x233510de"
        override:
          pwr:
            threshold: 160
            compare: low
          gclk:
            threshold: 1900
            compare: high
          smclk:
            threshold: 1900
            compare: high
  SmClkStuckLow:
    name: "SmClkStuckLow"
    description: "SM clock too low for long time"
    duration_threshold: 15m
    level: fatal
    check_items:
      smclk:
        threshold: 800
        compare: low
      gpuidle:
        threshold: 0
        compare: equal
      gpustate:
        threshold: 0
        compare: equal