{{- if eq .Values.mode "install-all" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-install-all
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-install-all
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      tolerations:
      - key: "node.kubernetes.io/unschedulable"
        operator: "Exists"
        effect: "NoSchedule"
      - key: scitix.ai/nodecheck
        operator: Exists
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ .Values.name }}-install-all
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          command: ["/bin/bash"]
          args:
            - "-c"
            - |-
              set -eux
              sleep 2
              cp /opt/sichek/dist/sicl-*.run /host/tmp/
              sicl_file=$(ls /host/tmp/sicl-*.run)
              chroot /host bash "/tmp/$(basename "$sicl_file")"
              {{- if eq .Values.os "ubuntu" }}
              cp /opt/sichek/dist/sichek_*_linux_amd64.deb /host/tmp/
              {{- else if eq .Values.os "centos" }}
              cp /opt/sichek/dist/sichek_*_linux_amd64.rpm /host/tmp/
              {{- end }}
              {{- if eq .Values.os "ubuntu" }}
              deb_file=$(ls /host/tmp/sichek_*_linux_amd64.deb)
              chroot /host dpkg -i "/tmp/$(basename "$deb_file")"
              {{- else if eq .Values.os "centos" }}
              rpm_file=$(ls /host/tmp/sichek_*_linux_amd64.rpm)
              chroot /host rpm -Uvh --force "/tmp/$(basename "$rpm_file")"
              {{- end }}
              {{- if ne .Values.defaultSpec "default" }}
              # Check if spec file exists locally, if not download from OSS
              if chroot /host test -f /var/sichek/config/{{ .Values.defaultSpec }}; then
                echo "Spec file exists locally, moving to default_spec.yaml"
                chroot /host mv /var/sichek/config/{{ .Values.defaultSpec }} /var/sichek/config/default_spec.yaml
              else
                echo "Spec file not found locally, downloading from OSS"
                chroot /host curl -o /var/sichek/config/default_spec.yaml "https://oss-ap-southeast.scitix.ai/hisys-sichek/specs/{{ .Values.defaultSpec }}"
              fi
              {{- end }}
              rm /host/tmp/sichek_*_linux_amd64.*
              rm /host/tmp/sicl-*.run
              echo "Install finished"
          volumeMounts:
            - name: host-root
              mountPath: /host
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
      restartPolicy: OnFailure
  completions: {{ .Values.batchjob.completions }}
  parallelism: {{ .Values.batchjob.parallelism }}
{{- end }}
