metrics:
  port: 19091

nvidia:
  query_interval: 10s
  cache_size: 5
  enable_metrics: true
  ignored_checkers:
    - "app-clocks"

infiniband:
  query_interval: 10s
  cache_size: 5
  enable_metrics: true
  ignored_checkers:
    - "net_operstate"

gpfs:
  query_interval: 10s
  cache_size: 5
  ignored_checkers: []

cpu:
  query_interval: 10s
  cache_size: 5
  enable_metrics: true

gpuevents:
  query_interval: 10s
  cache_size: 5
  nvsmi: false
  mock: false
  enable_metrics: true
  ignore_namespaces: []
  ignored_checkers: []

podlog:
  query_interval: 10s
  cache_size: 5

dmesg:
  query_interval: 10s
  cache_size: 5

syslog:
  query_interval: 10s
  cache_size: 5
  skip_percent: 100


nccltest:
  enable: true

pcie_topo:
  enable: true