nvidia:
  "0x233510de":
    name: NVIDIA H200 141GB HBM3e
    gpu_nums: 8
    gpu_memory: 141
    software:
      driver_version: ">=570.86.15"
      cuda_version: ">=12.8"
      vbios_version: "96.00.89.00.01"
      fabricmanager_version: "570.86.15"
    dependence:
      pcie_acs: disable
      iommu: off
      nv_peermem: enable
      nv_fabricmanager: active
      cpu_performance: enable
    MaxClock:
      Graphics: 1980 # MHz
      SM: 1980 # MHz
      Memory: 3201 # MHz
    nvlink:
      nvlink_supported: true
      active_nvlink_num: 18
      total_replay_errors: 0
      total_recovery_errors: 0
      total_crc_errors: 0
    state:
      persistence: enable
      pstate: 0
    memory_errors_threshold:
      remapped_uncorrectable_errors: 512
      sram_volatile_uncorrectable_errors: 0
      sram_aggregate_uncorrectable_errors: 4
      sram_volatile_correctable_errors: 10000000
      sram_aggregate_correctable_errors: 10000000
    temperature_threshold:
      gpu: 75
      memory: 95
infiniband:
  default:
    ib_devs:
      mlx5_0: eth0
      mlx5_1: eth1
      mlx5_2: eth2
      mlx5_3: eth3
      mlx5_4: eth4
      mlx5_5: eth5
      mlx5_6: eth6
      mlx5_7: eth7
    sw_deps:
      kernel_module:
        - "rdma_ucm"
        - "rdma_cm"
        - "ib_ipoib"
        - "mlx5_core"
        - "mlx5_ib"
        - "ib_uverbs"
        - "ib_umad"
        - "ib_cm"
        - "ib_core"
        - "mlxfw"
      ofed_ver: "MLNX_OFED_LINUX-24.10-2.1.8.0"
    pcie_acs: "disable"
    hca_specs:
      MT_0000000838:
        hardware:
          hca_type: "MT4129"
          board_id: "MT_0000000838"
          fw_ver: ">=28.39.2048" #"28.43.2566"
          vpd: "NVIDIA ConnectX-7 HHHL Adapter card, 400GbE / NDR IB (default mode), Single-port OSFP, PCIe 5.0 x16, Crypto Disabled, Secure Boot Enabled"
          net_port: 1
          port_speed: "400 Gb/sec (4X NDR)"
          phy_state: "LinkUp"
          port_state: "ACTIVE"
          net_operstate: "down"
          link_layer: "InfiniBand"
          pcie_width: "16"
          pcie_speed: "32.0 GT/s PCIe"
          pcie_tree_width: "32"
          pcie_tree_speed: "16"
          pcie_acs: "disable"
          pcie_mrr: "4096"
      DEL0000000036:
        hardware:
          hca_type: "MT4123"
          board_id: "DEL0000000036"
          fw_ver: ">=20.39.2048"
          vpd: "Nvidia ConnectX-7 Single Port Infiniband NDR OSFP Adapter"
          net_port: 1
          port_speed: "400 Gb/sec (4X NDR)"
          phy_state: "LinkUp"
          port_state: "ACTIVE"
          net_operstate: "down"
          link_layer: "InfiniBand"
          pcie_width: "16"
          pcie_speed: "32.0 GT/s PCIe"
          pcie_tree_width: "32"
          pcie_tree_speed: "16"
          pcie_acs: "disable"
          pcie_mrr: "4096"
      MT_0000000223: {}
  lh:
    ib_devs:
      mlx5_0: ib0
      mlx5_1: ib1
      mlx5_2: ib2
      mlx5_3: ib3
      mlx5_4: ib4
      mlx5_5: ib5
      mlx5_6: ib6
      mlx5_7: ib7
      mlx5_8: ib8
    sw_deps:
      kernel_module:
        - "rdma_ucm"
        - "rdma_cm"
        - "ib_ipoib"
        - "mlx5_core"
        - "mlx5_ib"
        - "ib_uverbs"
        - "ib_umad"
        - "ib_cm"
        - "ib_core"
        - "mlxfw"
      ofed_ver: "MLNX_OFED_LINUX-24.10-2.1.8.0"
    pcie_acs: "disable"
    hca_specs:
      MT_0000000838: {}
  css:
    ib_devs:
      mlx5_0: eth0
      mlx5_1: eth1
      mlx5_2: eth2
      mlx5_3: eth3
      mlx5_4: eth4
      mlx5_5: eth5
      mlx5_6: eth6
      mlx5_7: eth7
    sw_deps:
      kernel_module:
      - "rdma_ucm"
      - "rdma_cm"
      - "ib_ipoib"
      - "mlx5_core"
      - "mlx5_ib"
      - "ib_uverbs"
      - "ib_umad"
      - "ib_cm"
      - "ib_core"
      - "mlxfw"
      ofed_ver: "MLNX_OFED_LINUX-24.10-2.1.8.0"
    pcie_acs: "disable"
    hca_specs:
      MT_0000000838: {}
  Hercules:
    ib_devs:
      mlx5_0: eth0
      mlx5_1: eth1
      mlx5_2: eth2
      mlx5_3: eth3
      mlx5_4: eth4
      mlx5_5: eth5
      mlx5_6: eth6
      mlx5_7: eth7
    sw_deps:
      kernel_module:
      - "rdma_ucm"
      - "rdma_cm"
      - "ib_ipoib"
      - "mlx5_core"
      - "mlx5_ib"
      - "ib_uverbs"
      - "ib_umad"
      - "ib_cm"
      - "ib_core"
      - "mlxfw"
      ofed_ver: "MLNX_OFED_LINUX-24.10-2.1.8.0"
    pcie_acs: "disable"
    hca_specs:
      MT_0000000838: {}
pcie_topo:
  "0x233510de":
    numa_config:
    - node_id: 0 # NUMA0
      gpu_count: 4
      ib_count: 4

    - node_id: 1 # NUMA1
      gpu_count: 4
      ib_count: 4

    pci_switches:
    - gpu: 1
      ib: 1
      count: 8
  "0x232c10de":
      numa_config:
      - node_id: 0 # NUMA0
        gpu_count: 4
        ib_count: 4

      - node_id: 1 # NUMA1
        gpu_count: 4
        ib_count: 4

      pci_switches:
      - gpu: 1
        ib: 1
        count: 8
  "0x26b510de":
      numa_config:
      - node_id: 0 # NUMA0
        gpu_count: 4
        ib_count: 1

      - node_id: 1 # NUMA1
        gpu_count: 4
        ib_count: 0

      pci_switches:
      - gpu: 4
        ib: 1
        count: 1
      - gpu: 4
        ib: 0
        count: 1
 