infiniband:
  _base: &default_config
    ib_devs: &ib_devs
      - mlx5_0
      - mlx5_1
    sw_deps:
      kernel_module: &kernel_modules
        - "rdma_ucm"
        - "rdma_cm"
        - "ib_ipoib"
        - "mlx5_core"
        - "mlx5_ib"
        - "ib_uverbs"
        - "ib_umad"
        - "ib_cm"
        - "ib_core"
        - "mlxfw"
      pcie_acs: "disable"
  default:
    <<: *default_config
    eth_devs:
      - ibs18
      - ibs20
    sw_deps:
      <<: *sw_deps
      ofed_ver: ">=MLNX_OFED_LINUX-5.9-0.5.6.0"
    hca_specs:
      MT_0000001119:{}
  taurus: #cluster_name
    <<: *default_config
    eth_devs:
      - ibs18
      - ibs20
    sw_deps:
      <<: *sw_deps
      ofed_ver: "MLNX_OFED_LINUX-5.9-0.5.6.0"
    hca_specs:
      MT_0000001119: {}
      LNV0000000058: {}
      MT_0000000844: {}
      MT_0000000971:
        hardware:
          hca_type: "MT4129"
          board_id: "MT_0000000971"
          fw_ver: ">=28.39.1002" #curr:28.39.1002, spec:28.42.1000
          vpd: "P45466-001 / HPE InfiniBand NDR200 1-port OSFP PCIe5 x16 MCX75310AAS-HEAT Adapter"
          net_port: 1
          port_speed: "200 Gb/sec (2X NDR)"
          phy_state: "LinkUp"
          port_state: "ACTIVE"
          net_opstate: "down"
          link_layer: "InfiniBand"
          pcie_width: "16"
          pcie_speed: "16" #"16.0 GT/s PCIe"
          pcie_tree_width: "32"
          pcie_tree_speed: "16"
          pcie_acs: "disable"
          pcie_mrr: "4096"
          ofed_ver: "MLNX_OFED_LINUX-24.07-0.6.1.0"   
        perf:
          one_way_bw: 175 # Gbps
          avg_latency_us: 15.0 # us
      MT_0000000838:
        hardware:
          hca_type: "MT4129"
          board_id: "MT_0000000838"
          fw_ver: ">=28.36.1010" #curr:28.36.1010, 28.39.1002, spec:28.39.2048
          vpd: "NVIDIA ConnectX-7 adapter card, 400Gb/s NDR IB,, Single-port OSFP, PCIe 5.0 x16, Secure boot, No Crypto"
          net_port: 1
          port_speed: "400 Gb/sec (4X NDR)"
          phy_state: "LinkUp"
          port_state: "ACTIVE"
          net_opstate: "down"
          link_layer: "InfiniBand"
          pcie_width: "16"
          pcie_speed: "32" #"32.0 GT/s PCIe"
          pcie_tree_width: "32"
          pcie_tree_speed: "16"
          pcie_acs: "disable"
          pcie_mrr: "4096"
          ofed_ver: "MLNX_OFED_LINUX-23.10-1.1.9.0"
        perf:
          one_way_bw: 360 # Gbps
          avg_latency_us: 10.0 # us
  aquila: #cluster_name
    <<: *default_config
    eth_devs:
      - ibs2
      - ibs1
      - ibs0
    sw_deps:
      <<: *sw_deps
      ofed_ver: ">=MLNX_OFED_LINUX-5.9-0.5.6.0"
    hca_specs:
      LNV0000000019: {}
      MT_0000000223: {}
  cygnus: #cluster_name
    <<: *default_config
    eth_devs:
      - ibs15
      - ibs12
    sw_deps:
      <<: *sw_deps
      ofed_ver: "MLNX_OFED_LINUX-23.10-1.1.9.0"
    hca_specs:
      LNV0000000019: {}
      LNV0000000058: {}
      DEL0000000010: {}
      MT_0000000223: {}
      MT_0000000226: {}
  orion: #cluster_name
    <<: *default_config
    eth_devs:
      - ibs15
      - ibs12
    sw_deps:
      <<: *sw_deps
      ofed_ver: "MLNX_OFED_LINUX-23.10-1.1.9.0"
    hca_specs:
      LNV0000000019: {}
      LNV0000000058: {}
      MT_0000000223: {}
  sagi: #cluster_name
    <<: *default_config
    eth_devs:
      - ibs15
      - ibs12
    sw_deps:
      <<: *sw_deps
      ofed_ver: "MLNX_OFED_LINUX-23.10-1.1.9.0"
    hca_specs:
      MT_0000000223: {}
      MT_2420110034:
        hardware:
          hca_type: "MT4123"
          board_id: "MT_2420110034"
          fw_ver: "20.39.2048"
          vpd: "ConnectX-6 VPI adapter card, HDR IB (200Gb/s) and 200GbE, single-port QSFP56"
          net_port: 1
          port_speed: "200 Gb/sec (4X HDR)"
          phy_state: "LinkUp"
          port_state: "ACTIVE"
          net_operstate: "down"
          link_layer: "InfiniBand"
          pcie_width: "16"
          pcie_speed: "16" #16.0 GT/s PCIe"
          pcie_tree_width: "32"
          pcie_tree_speed: "16"
          pcie_acs: "disable"
          pcie_mrr: "4096"
        perf:
          one_way_bw: 175 # Gbps
          avg_latency_us: 15.0 # us
  cepheus: #cluster_name
    <<: *default_config
    eth_devs:
      - ibs15
      - ibs12
    sw_deps:
      <<: *sw_deps
      ofed_ver: "MLNX_OFED_LINUX-23.10-1.1.9.0"
    hca_specs:
      LNV0000000019: {}
      MT_0000000223: {}
      MT_0000000903: {}
  pegasus: #cluster_name
    <<: *default_config
    eth_devs:
      - ibs15
      - ibs12
    sw_deps:
      <<: *sw_deps
      ofed_ver: "MLNX_OFED_LINUX-23.10-1.1.9.0"
    hca_specs:
      LNV0000000019: {}
      MT_0000000223: {}
  centaurus: #cluster_name
    <<: *default_config
    eth_devs:
      - ibs15
      - ibs12
    sw_deps:
      <<: *sw_deps
      ofed_ver: "MLNX_OFED_LINUX-23.10-1.1.9.0"
    hca_specs:
      LNV0000000019: {}
      MT_0000000223: {}
      MT_0000000903: {}
      DEL0000000010: {}
  gemini: #cluster_name
    <<: *default_config
    eth_devs:
      - ibs15
      - ibs12
    sw_deps:
      <<: *sw_deps
      ofed_ver: "MLNX_OFED_LINUX-23.10-1.1.9.0"
    hca_specs:
      LNV0000000058: {}
      MT_0000000844: {}
      MT_0000000838:
        hca_type: "MT4129"
        board_id: "MT_0000000838"
        fw_ver: "28.39.2048"
        vpd: "NVIDIA ConnectX-7 adapter card, 400Gb/s NDR IB, Single-port OSFP, PCIe 5.0 x16, Secure boot, No Crypto"
        net_port: 1
        port_speed: "400 Gb/sec (4X NDR)"
        phy_state: "LinkUp"
        port_state: "ACTIVE"
        net_operstate: "down"
        link_layer: "InfiniBand"
        pcie_width: "16"
        pcie_speed: "32" #32.0 GT/s PCIe"
        pcie_tree_width: "32"
        pcie_tree_speed: "16"
        pcie_acs: "disable"
        pcie_mrr: "4096"
      perf:
        one_way_bw: 360 # Gbps
        avg_latency_us: 10.0 # us
