metrics:
  port: 19091

nvidia:
  query_interval: 30s
  cache_size: 5
  enable_metrics: true
  ignored_checkers:
    - "app-clocks"

infiniband:
  query_interval: 30s
  cache_size: 5
  enable_metrics: true
  ignored_checkers:
    - "check_net_operstate"
    - "check_ib_devs"
    - "check_ib_ofed"
    - "check_ib_fw"

ethernet:
  query_interval: 30s
  cache_size: 5
  enable_metrics: true

gpfs:
  query_interval: 30s
  cache_size: 5
  ignored_checkers: []

cpu:
  query_interval: 30s
  cache_size: 5
  enable_metrics: true

memory:
  query_interval: 30s
  cache_size: 5
  enable_metrics: true

gpu_custom_events:
  query_interval: 30s
  cache_size: 5
  nvsmi: false
  mock: false
  enable_metrics: true
  ignore_namespaces:
    - "ai-infra-user-xcwen"
    - "ai-infra-user-zhlin"
  ignored_checkers: []

nccl:
  query_interval: 30s
  cache_size: 5

dmesg:
  query_interval: 30s
  cache_size: 5