nvidia:
  "0x232910de":
    name: NVIDIA H20
    gpu_nums: 8
    gpu_memory: 96
    software:
      driver_version: ">=550.144.03"
      cuda_version: ">=12.4"
      vbios_version: "96.00.C3.00.02"
      fabricmanager_version: "550.144.03"
    dependence:
      pcie_acs: disable
      iommu: off
      nv_peermem: enable
      nv_fabricmanager: active
      cpu_performance: enable
    MaxClock:
      Graphics: 1980 # MHz
      SM: 1980 # MHz
      Memory: 2619 # MHz
    nvlink:
      nvlink_supported: true
      active_nvlink_num: 18
      total_replay_errors: 0
      total_recovery_errors: 0
      total_crc_errors: 0
    state:
      persistence: enable
      pstate: 0
    memory_errors_threshold:
      remapped_uncorrectable_errors: 512
      sram_volatile_uncorrectable_errors: 0
      sram_aggregate_uncorrectable_errors: 4
      sram_volatile_correctable_errors: 10000000
      sram_aggregate_correctable_errors: 10000000
    temperature_threshold:
      gpu: 75
      memory: 95
    perf:
      nccl-all-reduce-bw: 470 # GB/s
infiniband:
  default:
    ib_devs:
      mlx5_1: eth1
      mlx5_2: eth2
      mlx5_3: eth3
      mlx5_4: eth4
    sw_deps:
      kernel_module:
        - "rdma_ucm"
        - "rdma_cm"
        - "ib_ipoib"
        - "mlx5_core"
        - "mlx5_ib"
        - "ib_uverbs"
        - "ib_umad"
        - "ib_cm"
        - "ib_core"
        - "mlxfw"
      ofed_ver: "OFED-internal-23.10-1.1.9"
    pcie_acs: "disable"
    hca_specs: {}
hca:
  MT_0000001070:
    hardware:
      hca_type: "0"
      board_id: "MT_0000001070"
      fw_ver: "32.39.3808"
      vpd: "BlueField-3 E-series SuperNIC 400GbE/NDR single port QSFP112, PCIe Gen5.0 x16, 8 Cores, HHHL, Crypto Disabled, 16GB DDR5, BMC, Tall Bracket"
      net_port: 1
      port_speed: "400 Gb/sec (4X NDR)"
      phy_state: "LinkUp"
      port_state: "ACTIVE"
      net_operstate: "up"
      link_layer: "Ethernet"
      pcie_width: "16"
      pcie_speed: "32.0 GT/s PCIe"
      pcie_tree_width: "16"
      pcie_tree_speed: "32"
      pcie_acs: "disable"
      pcie_mrr: "4096"
    perf:
      one_way_bw: 360 # Gbps
      avg_latency_us: 10 # us
pcie_topo:
  "0x232910de":
      numa_config:
      - node_id: 0 # NUMA0
        gpu_count: 4
        ib_count: 2

      - node_id: 1 # NUMA1
        gpu_count: 4
        ib_count: 2

      pci_switches:
      - gpu: 2
        ib: 1
        count: 4