gpfs: 
  time_clock:
    name: "TimeClockError"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "Time-of-day may have jumped back"
    description: "Time clock error detected"
    level: "info"
    suggestion: "Reset the time clock with ntp"
  OS_lockup:
    name: "OSLockup"
    log_file: "/var/log/syslog"
    regexp: "(soft lockup)|(hard LOCKUP)"
    description: "OS lockup, may cause GPFS heartbeat fail and unmount"
    level: "info"
    suggestion: "Fix OS kernel and driver bugs"
  RDMA:
    name: "RDMAStatusError"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "(VERBS RDMA disabled)|(RDMA send error)|(VERBS RDMA: fatal async event)|(RDMA fatal connection error)"
    description: "node RDMA network down"
    level: "info"
    suggestion: "Check RDMA network and device"
  quorum_connection:
    name: "QuorumConnectionDown"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "Unable to contact any quorum"
    description: "connection with quorum node down"
    level: "critical"
    suggestion: "Check GPFS daemon network"
  tcp_state:
    name: "BadTcpState"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "Bad TCP state detected"
    description: "node TCP connection down"
    level: "info"
    suggestion: "Check GPFS daemon network"
  filesystem_unmount:
    name: "GPFSUnmount"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "unmounting file system"
    description: "node filesystem unmounted"
    level: "critical"
    suggestion: "Check GPFS status"
  expelled_from_cluster:
    name: "ExpelledFromGPFSCluster"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "This node is being expelled from the cluster"
    description: "node expelled from GPFS cluster"
    level: "critical"
    suggestion: "Check GPFS daemon network and status"
  unauthorized:
    name: "GPFSUnauthorized"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "cluster is not authorized"
    description: "node unauthorized for remote cluster"
    level: "critical"
    suggestion: "Check GPFS authorization status"
  bond0_lost:
    name: "Bond0Lost"
    log_file: "/var/log/syslog"
    regexp: "bond0: now running without any active interface"
    description: "bond0 not active"
    level: "critical"
    suggestion: "Check GPFS ether network"
  RDMA_start_failed:
    name: "RDMA_start_failed"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "VERBS RDMA failed to start"
    description: "RDMA start failed"
    level: "critical"
    suggestion: "Check RDMA network and device"
  incompatible_GPFS_version:
    name: "incompatible_GPFS_version"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "daemon versions were not compatible"
    level: "info"
    suggestion: "Check and update GPFS version"
  autoload_failed:
    name: "autoload_failed"
    log_file: "/var/adm/ras/mmfs.log.latest"
    regexp: "GPFS environment cannot be initialized"
    level: "info"
    suggestion: "Check node GPFS and mmstartup"