dmesg: 
  SysOOM:
    name: "SysOOM"
    log_file: "/tmp/sichek.dmesg.log"
    description: "oom error in dmesg"
    regexp: 'Out of memory:'
    level: info 
  CgroupOOM:
    name: "CgroupOOM"
    log_file: "/tmp/sichek.dmesg.log"
    description: "oom error in dmesg"
    regexp: 'Memory cgroup out of memory'
    level: info
  NVSXID:
    name: "NVSXID"
    log_file: "/tmp/sichek.dmesg.log"
    description: "nv sxid error in dmesg"
    regexp: 'SXid.*?: (\d+),'
    level: info
  NCCLSegFault:
    name: "NCCLSegFault"
    log_file: "/tmp/sichek.dmesg.log"
    description: "libnccl segment fault error in dmesg"
    regexp: '.*segfault at.*in libnccl*'
    level: info
  NvErrResetRequired:
    name: "NvErrResetRequired"
    log_file: "/tmp/sichek.dmesg.log"
    description: "GspRmAlloc failed, Reset required [NV_ERR_RESET_REQUIRED]"
    regexp: 'Reset required \[NV_ERR_RESET_REQUIRED\]'
    level: critical
  NvErrObjectNotFound:
    name: "NvErrObjectNotFound"
    log_file: "/tmp/sichek.dmesg.log"
    description: "Requested object not found [NV_ERR_OBJECT_NOT_FOUND] in dmesg"
    regexp: 'NV_ERR_OBJECT_NOT_FOUND'
    level: critical
  LibcSegFault:
    name: "LibcSegFault"
    log_file: "/tmp/sichek.dmesg.log"
    description: "libc segment fault error in dmesg"
    regexp: '.*segfault at.*in libc.*'
    level: info